urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import FavoloView
from . import views

app_name = 'favolo'

# 第１引数にはアドレスを指定
# 第２引数には使用するビュー関数を指定
# 第３引数にはこのパス自体の名前を指定

#path('login/', auth_views.LoginView.as_view(template_name="favolo/login.html"), name='login'),
#path('logout/', auth_views.LogoutView.as_view(next_page="favolo:test"), name='logout'),

urlpatterns = [
    path(r'', FavoloView.as_view(), name='index'),
    path('result', views.result, name='result'),
    path('profile', views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.account_login, name='login'),
    path('logout/', views.account_logout, name='logout'),
    path('settings/username', views.settings_username, name='username'),
    path('settings/password', views.settings_password, name='password'),
    path('settings/design', views.settings_design, name='design'),
    path('settings/introduction', views.settings_introduction, name='introduction'),
    path('settings/tags', views.settings_tags, name='tags'),
    path('settings', views.settings, name='settings'),
    path('all', views.all_pages, name='all'),
    path('<str:accesskey>', views.pages, name='accesskey'),
    path('<str:accesskey>/like/', views.likes, name="likes"),
    path('<str:accesskey>/follow/', views.follows, name="follows"),
]

templates/favolo/all.html
<!-- 静的ファイルの使用-->
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'favolo/css/articles.css' %}" />
    </head>
    <body>
        <header>
            <div class="header-left">
                <div class="logo">
                    <h3>{{ title }}</h3>
                </div>
            </div>
            <div class="header-right">
                <!-- プロフィール画像 -->
                <a href="{% url 'favolo:result' %}"><img src="{{ page_profile_image }}" alt=""></a>
                <nav class="global-nav">
                    <ul class="global-nav__list">
                      <li class="global-nav__item"><a href="{% url 'favolo:result' %}">{{ username }}</a></li>
                      <li class="global-nav__item"><a href="">{{ account }}</a></li>
                      <li class="global-nav__item"><a href="{% url 'favolo:settings' %}">設定</a></li>
                      <li class="global-nav__item"><a href="{% url 'favolo:all' %}">記事一覧</a></li>
                      <li class="global-nav__item"><a href="">利用規約</a></li>
                      <li class="global-nav__item"><a href="">ドキュメント</a></li>
                      <li class="global-nav__item"><a href="{% url 'favolo:logout' %}">ログアウト</a></li>
                    </ul>
                </nav>
                    <div class="hamburger" id="js-hamburger">
                        <span class="hamburger__line hamburger__line--1"></span>
                        <span class="hamburger__line hamburger__line--2"></span>
                        <span class="hamburger__line hamburger__line--3"></span>
                    </div>
                    <div class="black-bg" id="js-black-bg"></div>
            </div>
        </header>
        <div class="archive">
            <a href="{% url 'favolo:accesskey' '10aefv8927buid2469' %}">
            <div class="card card-skin">
                <div class="card__imgframe"></div>
                <div class="card__textbox">
                  <div class="card__titletext">
                    ホテル好きのぼくが選ぶ京都のおすすめホテル
                  </div>
                  <div class="card__overviewtext">
                    <img class="card__profile" src="{{ page_profile_image }}" alt="">
                </div>
                </div>
            </div>
            </a>
            <a href="{% url 'favolo:accesskey' '10lOAy9729ryQC0586' %}">
            <div class="card card-skin">
                <div class="card__imgframe"></div>
                <div class="card__textbox">
                  <div class="card__titletext">
                    Favoにタイトルをつけてみよう！
                  </div>
                  <div class="card__overviewtext">
                    <img class="card__profile" src="{{ page_profile_image }}" alt="">
                  </div>
                </div>
            </div>
            </a>
            <a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">
            <div class="card card-skin">
                <div class="card__imgframe"></div>
                <div class="card__textbox">
                  <div class="card__titletext">
                    Favoにタイトルをつけてみよう！
                  </div>
                  <div class="card__overviewtext">
                    <img class="card__profile" src="{{ page_profile_image }}" alt="">
                </div>
                </div>
            </div>
            </a>
            <div class="card card-skin">
                <div class="card__imgframe"></div>
                <div class="card__textbox">
                  <div class="card__titletext">
                    タイトルがはいります。タイトルがはいります。
                  </div>
                  <div class="card__overviewtext">
                    <img class="card__profile" src="{{ page_profile_image }}" alt="">
                </div>
                </div>
            </div>
            <div class="card card-skin">
                <div class="card__imgframe"></div>
                <div class="card__textbox">
                  <div class="card__titletext">
                    タイトルがはいります。タイトルがはいります。
                  </div>
                  <div class="card__overviewtext">
                    <img class="card__profile" src="{{ page_profile_image }}" alt="">
                </div>
                </div>
            </div>
            <div class="card card-skin">
                <div class="card__imgframe"></div>
                <div class="card__textbox">
                  <div class="card__titletext">
                    タイトルがはいります。タイトルがはいります。
                  </div>
                  <div class="card__overviewtext">
                    <img class="card__profile" src="{{ page_profile_image }}" alt="">
                </div>
                </div>
            </div>
        </div>
        <div class="footer">
          <div class="footer__box">
            <p>ロゴが入ります</p>
          </div>
          <div class="footer__box">
            <p class="footer__title">About</p>
            <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">Favoloについて</a></p>
            <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">使い方</a></p>
            <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">よくある質問</a></p>
            <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">運営者情報</a></p>
          </div>
          <div class="footer__box">
            <p class="footer__title">Develoment</p>
            <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">開発者に向けて</a></p>
            <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">ドキュメント</a></p>
            <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">Github</a></p>
          </div>
          <div class="footer__box">
            <p class="footer__title">Legal</p>
            <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">利用規約</a></p>
            <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">プライバシーポリシー</a></p>
          </div>
        </div>

        <!-- Swiper END -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.4.5/js/swiper.min.js"></script>
        <script type="text/javascript" src="{% static 'favolo/js/slide.js' %}"></script>
        <!-- JQuery -->
        <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    </body>
</html>

templates/favolo/database.html
<!-- 静的ファイルの使用-->
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'favolo/css/index.css' %}" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    </head>
    <body>
        <p>これはdatabase.htmlです</p>
        {% for item in rows %}
        {{ item }}
        {% endfor %}
        {% for i in row %}
        {{ i }}
        {% endfor %}
    </body>
</html>

templates/favolo/index.html
<!-- 静的ファイルの使用-->
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'favolo/css/index.css' %}" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    </head>
    <body>
      <div class="box">
        <!-- 送り先のURLを指定する-->
        <!-- {{ form }} -->
        <form action="{% url 'favolo:result' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-warning my-2" type="submit" value="LOGIN">
        <!-- <button>login</button> -->
        </form>
      </div>
    </body>
</html>

templates/favolo/login.html
<!-- 静的ファイルの使用-->
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'favolo/css/index.css' %}" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    </head>
    <body>
        <div class="title-container">
            <div class="title">ログイン</div>
            <div class="progress" style="height: 3px;">
                <div class="progress-bar" role="progressbar" style="width: 50%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
        <div class="box">
            <form action="{% url 'favolo:login' %}" method="post">
                {% csrf_token %}
                <div class="field">
                    {{ form.email }}
                </div>
                <div class="field">
                    {{ form.password }}
                </div>
                <div class="main-button">
                    <input class="btn btn-primary my-2" type="submit" value="ログイン">
                </div>   
            </form>
            <div class="sub-button">
                <p>or <a href= "{% url 'favolo:signup' %}" class="btn btn-primary btn-sm" role="button">サインアップ</a></p>
            </div>
        </div>
    </body>
</html>

templates/favolo/profile.html
<!-- 静的ファイルの使用-->
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'favolo/css/index.css' %}" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    </head>
    <body>
        <h1>アカウント確認</h1>
        <h2>{{ email }}宛に確認メールを送りました</h2>
        <p>※現在実装できていません</p>
        <p>お名前：{{ username }}</p>
        <p>Twitter：{{ account }}</p>
        <a href="{% url 'favolo:result' %}">さっそく使ってみる！</a>
    </body>
</html>

templates/favolo/result.html
<!-- 静的ファイルの使用-->
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'favolo/css/style.css' %}" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.4.5/css/swiper.css">
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    </head>
    <body>
        <header>
            <div class="header-left">
                <div class="header-left-logo">
                    <h3>{{ title }}</h3>
                </div>
            </div>
            <div class="header-right">
                <!-- お知らせアイコン -->
                <div class="header-right-icon"><i class="far fa-bell fa-lg"></i></div>
                <!-- プロフィール画像 -->
                <a href="{% url 'favolo:result' %}"><img src="{{ page_profile_image }}" alt=""></a>
                <nav class="global-nav">
                    <ul class="global-nav__list">
                      <li class="global-nav__item"><a href="{% url 'favolo:result' %}">{{ username }}</a></li>
                      <li class="global-nav__item"><a href="https://twitter.com/{{ account }}">{{ account }}</a></li>
                      <li class="global-nav__item"><a href="{% url 'favolo:settings' %}">設定</a></li>
                      <li class="global-nav__item"><a href="{% url 'favolo:all' %}">記事一覧</a></li>
                      <li class="global-nav__item"><p>{{ follow }} フォロー中</p></li>
                      <li class="global-nav__item"><p>{{ followed }} フォロワー</p></li>
                      <li class="global-nav__item"><a href="{% url 'favolo:logout' %}">ログアウト</a></li>
                    </ul>
                </nav>
                    <div class="hamburger" id="js-hamburger">
                        <span class="hamburger__line hamburger__line--1"></span>
                        <span class="hamburger__line hamburger__line--2"></span>
                        <span class="hamburger__line hamburger__line--3"></span>
                    </div>
                    <div class="black-bg" id="js-black-bg"></div>
            </div>
        </header>
        <div class="introduction">
            <div class="introduction__textbox">
                <h2>{{ page_title }}</h2>
                <p class="comment">by {{ page_name }}</p>
                <p class="comment">{{ page_comment }}</p>
            </div>
            <div class="introduction__sharebox">
                <div class="introduction__tagsbox">
                    {% if page_tag_name %}
                    <p class="tag"><i class="fas fa-tags"></i> {{ page_tag_name }}</p>
                    {% endif %} 
                </div>
                <div class="introduction__buttonbox">
                    <!-- いいねボタン -->
                    <div class="introduction__icon">
                        {% if page_liked_status is False %}
                        <p><a href="{% url 'favolo:likes' page_accesskey %}"><i class="far fa-heart fa-lg icon-gray"></i></a></p>
                        {% else %}
                        <p><a class="red" href="{% url 'favolo:likes' page_accesskey %}"><i class="fas fa-heart fa-lg icon-red"></i></a></p>
                        {% endif %}
                    </div>
                    <div class="favorite__number">{{ page_likes }}</div>
                    <!-- フォローボタン -->
                    {% if page_followed_status_code is 2 %}
                    <div class="introduction__icon">
                        {% if page_followed_status is False %}
                        <p><a href="{% url 'favolo:follows' page_accesskey %}"><i class="fas fa-check fa-lg icon-gray"></i> </a></p>
                        {% else %}
                        <p><a href="{% url 'favolo:follows' page_accesskey %}"><i class="fas fa-check fa-lg icon-blue"></i> </a></p>
                        {% endif %}                       
                    </div>
                    {% endif %}
                    <!-- リンクコピーボタン -->
                    <div class="introduction__icon">
                        <p><i class="fas fa-share-alt fa-lg icon-gray"></i></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="archive">
            {% for text, image, id in list %}
            <!-- 一つ一つの投稿を表示　-->
            <div class="article">
                <!-- スライドの大枠　-->
                <div class="hero">
                    <!-- 画像のとき -->
                    {% if id == 1 %}
                    <!-- スライド部分開始　-->
                    <div class="swiper-container">
                        <!-- メイン表示部分　-->
                        <div class="swiper-wrapper">
                        <!-- 各スライド -->
                        {% for url in image %}
                            <div class="swiper-slide"><img src="{{ url }}" alt=""></div>
                        {% endfor %}
                        </div>
                    </div>
                    <!-- 動画のとき -->
                    {% elif id == 2 %}
                    <video src="{{ image }}" width="100%" height="400px" loop autoplay muted></video>
                    <!-- 画像も動画もないとき-->
                    {% elif id == 3 %}
                    {% endif %}
                </div>
                <div class="article-textbox">
                    <p>{{ text }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="footer">
            <div class="footer__box">
              <h3>Favolo</h3>
            </div>
            <div class="footer__box">
              <p class="footer__title">About</p>
              <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">Favoloについて</a></p>
              <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">使い方</a></p>
              <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">よくある質問</a></p>
              <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">運営者情報</a></p>
            </div>
            <div class="footer__box">
              <p class="footer__title">Develoment</p>
              <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">開発者に向けて</a></p>
              <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">ドキュメント</a></p>
              <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">Github</a></p>
            </div>
            <div class="footer__box">
              <p class="footer__title">Legal</p>
              <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">利用規約</a></p>
              <p><a href="{% url 'favolo:accesskey' '10oGQX4017aKeT4457' %}">プライバシーポリシー</a></p>
            </div>
          </div>

        <!-- Swiper END -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.4.5/js/swiper.min.js"></script>
        <script type="text/javascript" src="{% static 'favolo/js/slide.js' %}"></script>
        <!-- JQuery -->
        <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <!-- api_likes.js END-->
        <script type="text/javascript" src="{% static 'favolo/js/liked.js' %}"></script>
    </body>
</html>

templates/favolo/settings.html
<!-- 静的ファイルの使用-->
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'favolo/css/settings.css' %}" />
    </head>
    <body>
        <header>
            <div class="header-left">
                <div class="logo">
                    <p>{{ title }}</p>
                </div>
            </div>
            <div class="header-right">
                <!-- プロフィール画像 -->
                <a href="{% url 'favolo:result' %}"><img src="{{ page_profile_image }}" alt=""></a>
                <nav class="global-nav">
                    <ul class="global-nav__list">
                      <li class="global-nav__item"><a href="{% url 'favolo:result' %}">{{ username }}</a></li>
                      <li class="global-nav__item"><a href="">{{ account }}</a></li>
                      <li class="global-nav__item"><a href="{% url 'favolo:settings' %}">設定</a></li>
                      <li class="global-nav__item"><a href="{% url 'favolo:all' %}">記事一覧</a></li>
                      <li class="global-nav__item"><a href="">利用規約</a></li>
                      <li class="global-nav__item"><a href="">ドキュメント</a></li>
                      <li class="global-nav__item"><a href="{% url 'favolo:logout' %}">ログアウト</a></li>
                    </ul>
                </nav>
                    <div class="hamburger" id="js-hamburger">
                        <span class="hamburger__line hamburger__line--1"></span>
                        <span class="hamburger__line hamburger__line--2"></span>
                        <span class="hamburger__line hamburger__line--3"></span>
                    </div>
                    <div class="black-bg" id="js-black-bg"></div>
            </div>
        </header>
        <div class="leftNavigation">
            <ul class="settings-nav">
                <li class="setting-li"><a class="active" href="{% url 'favolo:username' %}">ユーザー</a></li>
                <li class="setting-li"><a href="{% url 'favolo:password' %}">パスワード</a></li>
                <li class="setting-li"><a href="{% url 'favolo:design' %}">デザイン</a></li>
                <li class="setting-li"><a href="{% url 'favolo:introduction' %}">タイトル/コメント</a></li>
                <li class="setting-li"><a href="{% url 'favolo:tags' %}">タグ</a></li>
            </ul>
        </div>
        <div class="rightContent">
            <h1>ユーザーネームの変更</h1>
            <p>たとえばユーザーネームの変更ができます</p>
        </div>
        <!-- Swiper END -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.4.5/js/swiper.min.js"></script>
        <script type="text/javascript" src="{% static 'favolo/js/slide.js' %}"></script>
    </body>
</html>

templates/favolo/signup.html
<!-- 静的ファイルの使用-->
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'favolo/css/index.css' %}" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    </head>
    <body>
        <div class="title-container">
            <div class="title">サインアップ</div>
            <div class="progress" style="height: 3px;">
                <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
        <div class="box">
            <form action="{% url 'favolo:signup' %}" method="post">
                {% csrf_token %}
                <div class="field">
                    {{ form.username }}
                </div>
                <div class="field">
                    {{ form.account }}
                </div>
                <div class="field">
                    {{ form.email }}
                </div>
                <div class="field">
                    {{ form.enter_password }}
                </div>
                <div class="field">
                    {{ form.retype_password }}
                </div>
                <div class="main-button">
                    <input class="btn btn-primary my-2" type="submit" value="サインアップ">
                </div>
            </form>
            <div class="note">登録することで利用規約に同意するものとします。</div>
            <div class="sub-button">
                <p>or <a href= "{% url 'favolo:login' %}" class="btn btn-primary btn-sm" role="button">ログイン</a></p>
            </div>
        </div>
    </body>
</html>